// packages/hotlight-svelte/src/lib/Input.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import { config, search } from "../store";

  onMount(() => input.focus());

  let input;
  let value: string = "";

  const skip = (e: KeyboardEvent) => {
    const doNothing = ["Meta", "Tab", "Shift", "ArrowLeft", "ArrowRight", "Escape"];
    if(doNothing.includes(e.key)) {
      return
    }

    if(e.key === "Enter") {
      //this.doTrigger();
      e.preventDefault();
      return;
    }

    if(e.key === "ArrowUp") {
      search.choose($search.index - 1);
      e.preventDefault();
      return
    } else if(e.key === "ArrowDown") {
      search.choose($search.index + 1);
      e.preventDefault();
      return
    }
  }

  const performSearch = (e: KeyboardEvent) => {
    const skip = ["ArrowRight", "ArrowLeft"];
    if(skip.includes(e.key)) {
      return
    }

    if(e.key === "Escape") {
      e.preventDefault();
      if(
        $search.query === ""
        // && store.state.parents.length === 0
      ) {
        config.hide();
        return
      } else {
        //this.engine.search("");
        search.reset();
      }
    }

    const prevent = ["ArrowUp", "ArrowDown", "Enter", "Meta"];
    if(prevent.includes(e.key)) {
      e.preventDefault();
    } else {
      const val = value.trim();
      //search.search(val);
      console.log("search", $search.query.trim());
      
      //this.engine.search(val);
    }
  };

</script>

<svelte:options tag="hotlight-input" />

<form
  role="search"
  novalidate
  autocomplete="off"
>
  <div id="parents-container"></div>
  <input
    on:keydown={skip}
    on:keyup={performSearch}
    bind:this={input}
    bind:value={$search.query}
    id="input"
    type="text"
    class="text-input"
    autocomplete="off"
    spellcheck="false"
    placeholder={$config.placeholder}
  />
</form>

<style>
  form {
    display: flex;
    margin: 0;
  }
  input {
    flex-grow: 1;
    font-size: 18px;
    color: var(--hl-text-color, rgba(255, 255, 255, 80%));
    padding: 10px;
    border: none;
    background: transparent;
  }
  input:placeholder {
    color: var(--hl-input-placeholder-color, white);
  }
  input:focus {
    outline: none;
  }

  #parents-container {
    display: flex;
  }
  /*
  #parents-container.show div.parent:last-of-type {
    max-width: 100px;
    overflow: hidden;
  }
  .parent:last-of-type {
    max-width: 0;

    transition: max-width 0.2s;
  }
  .parent-inner {
    display: block;
    background: red;
    color: white;
    padding: 2px;
  }
  */
</style>

// packages/hotlight-wc/src/input.ts
import { Actions } from "./typings";

export class Input extends HTMLElement {
  constructor() {
    super();
    this.component = this
      .attachShadow({
        mode: 'open'
      })

    const color = getComputedStyle(window.document.documentElement)
    .getPropertyValue("--hl-text-color");
    console.log(color, window.document)

    this.component.appendChild(template.content.cloneNode(true));

    this.parentsContainer = this.component.getElementById("parents-container");
    this.input = this.component.getElementById("input");

  }

  private renderParents() {
    if(this.lastParentCount < this._parents.length) {
      this.parentsContainer.classList.remove("show");
    }
    this.lastParentCount = this._parents.length;
    const frag = document.createDocumentFragment();

    this._parents.forEach(action => {
      const item = parentTemplate.content.cloneNode(true) as HTMLElement;
      item.querySelector(".parent-inner").innerHTML = action.title;
      frag.appendChild(item);
    });

    this.parentsContainer.innerHTML = "";
    this.parentsContainer.appendChild(frag);
    setTimeout(() => {
      this.parentsContainer.classList.add("show");
    }, 0);
  }

  clear() {
    this.input.value = "";
  }

  set placeholder(value: string) {
    this.setAttribute("placeholder", value);
    this.input.setAttribute("value", value);
  }

  private component: any;
  private input: HTMLInputElement;
  private parentsContainer: HTMLDivElement;
  private _parents: Actions;
  private lastParentCount: number;

  get value() {
    return this.input.value;
  }

  set value(value: string) {
    this.input.value = value;
  }

  set parents(value: Actions) {
    console.log(value)
    this._parents = value;
    this.renderParents();
  }

  get parents() {
    return this.parents;
  }

  focus() {
    this.input.focus();
  }
}

const template = document.createElement("template");
template.innerHTML = `
  <form
    role="search"
    novalidate
    autocomplete="off"
  >
    <div id="parents-container"></div>
    <input
      id="input"
      type="text"
      class="text-input"
      autocomplete="off"
      spellcheck="false"
    />
  </div>

  <style>
    form {
      display: flex;
      margin: 0;
    }
    input {
      flex-grow: 1;
      font-size: 18px;
      color: var(--hl-text-color);
      padding: 10px;
      border: none;
      background: transparent;
    }
    input:placeholder {
      color: white;
    }
    input:focus {
      outline: none;
    }

    #parents-container {
      display: flex;
    }
    #parents-container.show div.parent:last-of-type {
      max-width: 100px;
      overflow: hidden;
    }
    .parent:last-of-type {
      max-width: 0;

      transition: max-width 0.2s;
    }
    .parent-inner {
      display: block;
      background: red;
      color: white;
      padding: 2px;
    }
  </style>
`;

const parentTemplate = document.createElement("template");
parentTemplate.innerHTML = `
  <div class="parent" style="padding: 10px; ">
    <span class="parent-inner"></span>
  </div>
`
