// packages/hotlight-wc/src/results.ts
import { Action, Actions } from "./typings";
import { underscore } from "./utils";

export class Results extends HTMLElement {
  constructor() {
    super();
    this.component = this
      .attachShadow({
        mode: 'open'
      })

    this.component.appendChild(template.content.cloneNode(true));
    this.results = this.component.getElementById("results");  
    this.list = this.component.getElementById("list");  
    this.activeHit = this.component.getElementById("active-hit");  
    this.actionTemplate = actionTemplate;

    this.results.addEventListener("mouseover", (e: MouseEvent) => {
      if(e.target.classList.contains("hit")) {
        const index = Array.from(e.target.parentNode.children).indexOf(e.target);
        this.hoverHit(index);
      }
    });

  }

  private _query: string;

  renderItem(action: Action, index: number) {
    const item = this.actionTemplate.content.cloneNode(true) as HTMLElement;
    const title = item.querySelector(".title");
    if(index === this.activeIndex) {
      title.classList.add("active");
    }
    title.innerHTML = underscore(this._query, action.title);
    return item;
  }

  set query(value: string) {
    this._query = value;
  }

  set actions(value: Actions) {
    this._actions = value;
    this.renderItems(value);
    if(value.length === 0) {
      this.moveActiveHit(-1);
    }
  }

  get actions() {
    return this._actions;
  }

  set activeIndex(value: number) {
    this.moveActiveHit(value);
  }

  hoverHit(index: number) {
    this.moveActiveHit(index);
    this.component.dispatchEvent(new CustomEvent("hover-hit", {
      detail: index,
      bubbles: true,
      composed: true
    }));
  }

  moveActiveHit(index: number) {
    if(index === -1) {
      this.activeHit.classList.add("hidden");
    } else {
      this.activeHit.classList.remove("hidden");
    }

    if(!this._actions) {
      return; // happens if a query is triggered from ie initialState before ref is there
    }

    const { top: resultsTop, height: resultsHeight } = this.results.getBoundingClientRect();
    const child = this.results.children[index];
    if(child) {
      const currentlyActive = this.results.querySelector(".active");
      if(currentlyActive) {
        currentlyActive.classList.remove("active");
      }
      child.classList.add("active");

      const { top } = child.getBoundingClientRect();
      const height = 32;

      const offset = resultsTop - top;

      if(top > resultsTop + resultsHeight) {
        this.results.scrollTo({ top: (height*index), behavior: "auto" });
      } else if(offset > 0) {
        this.results.scrollTo({ top: (height*index), behavior: "auto" });
      }

      if(this.activeHit) {
        this.activeHit.classList.remove("hidden");
        this.activeHit.style.transform = `translateY(${height*index}px)`;
        this.activeHit.style.height = `${height}px`; 
      }
    }
  }

  renderItems(actions: Actions) {
    const frag = document.createDocumentFragment();
    actions.forEach((action, index) => {
      frag.appendChild(this.renderItem(action, index));
    });

    if(this.results.children.length > 0) {
      this.results.innerHTML = '';
      this.results.appendChild(frag);
    } else {
      this.results.appendChild(frag);
    }
    this.results.classList.remove("enter-active");
  }

  private component: any;
  private list: HTMLElement;
  private results: HTMLElement;
  private activeHit: HTMLElement;
  private actionTemplate: HTMLTemplateElement;
  private _actions: Actions;
}

//const predefinedTemplate = document.body.querySelector("#hotlight-action") as HTMLTemplateElement;
//const actionTemplate = predefinedTemplate ? predefinedTemplate : document.createElement("template");

const actionTemplate = document.createElement("template");
actionTemplate.innerHTML = `
  <div
    tabindex="0"
    class="hit"
  >
    <div class="title">
      Title       
    </div>
    <span class="category"></span>
  </div>
`;
    //<ResultLocation trigger={trigger} />

const template = document.createElement("template");
template.innerHTML = `
  <div id="list" class="enter-active">
    <div id="results"></div>
    <div id="active-hit"></div>
  </div>

  <style>
    #list {
      position: relative;
    }

    .results {
      position: relative;
      max-height: 200px;
      overflow-y: auto;
    }

    .hit {
      display: flex;
      align-items: center;
      position: relative;
      font-size: 16px;
      padding: 0 20px;
      cursor: pointer;
      color: grey;
      height: 32px;

      transition: color 0.2s ease;
    }
    .hit-inner {
      position: absolute;
      z-index: 10;
    }
    .enter-active .active {
      transition: none;
    }

    .active {
      color: white;
    }
    #active-hit {
      display: flex;
      position: absolute;
      top: 0;
      z-index: 1;
      cursor: pointer;
      pointer-events: none;

      transition: transform 0.05s ease, color 0.1s ease;

      background: rgba(255, 255, 255, 10%);
      border-radius: 3px;
      height: 32px;
      width: calc(100% - 20px);
      margin: 0 10px;
    }
    #active-hit.hidden {
      background: rgba(255, 255, 255, 0);
    }

    .category {
      color: #999;
    }

    /* underscoring matches */
    .u {
      text-decoration: underline;
      font-weight: bold;
    }
  </style>
`;

// packages/hotlight-svelte/src/lib/Results.svelte
<script lang="ts">
	import { fade } from 'svelte/transition';

  import { search, config } from "../store";
  import { underscore } from "../utils";

  let resultsRef;

  const pick = () => {
    search.perform();
  }

  const activateHit = (index) => {
    search.choose(index);
  }

  let style;
  $: {
    if(resultsRef && resultsRef.children) {
      const child = resultsRef.children[$search.index];
      let h = $search.index > -1 && child ? window.getComputedStyle(child).height : "0";
      style = `height: ${h}; transform: translateY(${parseInt(h)*$search.index}px)`;
    }
  }
</script>

<svelte:options tag="hotlight-results" />
<span class="u"></span><!-- keep to keep the css class -->

<div id="list" class="enter-active">
  <div id="results" bind:this={resultsRef}>
    {#each $search.results as result, index}
      <div
        tabindex="0"
        class="hit"
        on:click|preventDefault={pick}
        on:mouseover={() => activateHit(index)}
        on:focus={() => activateHit(index)}
      >
        <div class="title" class:active={index === $search.index}>
          {@html underscore($search.query, result.title)}       
        </div>
        <div class="alias">
          {@html underscore($search.query, result.alias)}       
        </div>
        <span class="category"></span>
      </div>
    {/each}

    {#if $search.index > -1 && $search.results.length > 0}
      <div id="active-hit" style="{style}" transition:fade="{{ duration: $config.transitions ? 150 : 0 }}"></div>
    {/if}

  </div>

  {#if $search.preview}
    <div id="preview">
      <div>
        {@html $search.preview}
      </div>
    </div>
  {/if}

</div>

<style>
#list {
  position: relative;
  display: flex;
  flex-direction: row;
}

#results {
  position: relative;
  width: 100%;
  max-height: 224px;
  overflow-y: auto;
}

#preview {
  width: 200px;
}

.hit {
  display: flex;
  align-items: center;
  position: relative;
  font-size: 16px;
  padding: 0 20px;
  cursor: pointer;
  color: var(--hl-hit-color, gray);
  height: 32px;

  transition: color 0.2s ease;
}
.hit-inner {
  position: absolute;
  z-index: 10;
}
.alias {
  font-size: 14px;
  margin-left: 10px;
}
.enter-active .active {
  transition: none;
}

.active {
  color: var(--hl-active-hit-color, rgba(255, 255, 255, 70%));
}
#active-hit {
  display: flex;
  position: absolute;
  top: 0;
  z-index: 1;
  cursor: pointer;
  pointer-events: none;

  transition: transform 0.05s ease, color 0.1s ease;

  color: var(--hl-active-hit-color, white);
  background: var(--hl-active-hit-background, rgba(255, 255, 255, 10%));
  border-radius: var(--hl-active-hit-radius, 3px);
  height: 32px;
  width: calc(100% - 20px);
  margin: 0 10px;
}
#active-hit.hidden {
  background: rgba(255, 255, 255, 0);
}

.category {
  color: #999;
}

.u {
  text-decoration: var(--hl-underscore-decoration, none);
  font-weight: var(--hl-underscore-font-weight, bold);
  color: var(--hl-underscore-color, rgba(255, 255, 255, 90%));
}
</style>
